---

services:
  redis:
    image: fisher772/redis
    container_name: redis
    hostname: redis
    restart: unless-stopped
    environment:
      TZ: ${EKB}
    volumes:
      - redis_conf:/usr/local/etc/redis/conf.d
    networks:
      - redis

volumes:
  redis_conf:

networks:
  redis:
    external: true
